name = "pagezone-gateway"
compatibility_date = "2024-12-01"

account_id = "152595c1bd678c6eb1ccb2aa4b1e2643"

[vars]
ENVIRONMENT = "production"

# R2 Bucket para imágenes
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "pagezone-assets"

# KV para rate limiting y stats
# [[kv_namespaces]] - se crea automáticamente en el primer deploy

[[kv_namespaces]]
binding = "GUARDIAN_KV"
id      = "36c2ec8740c442b88e31ef8f42d728f6"